// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnweucrthasvbgzvsyun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZud2V1Y3J0aGFzdmJnenZzeXVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODIxMzEsImV4cCI6MjA3MDA1ODEzMX0.1J5Rf4KHBCh_Sla3aMxuFdYaAfW3KwVN5whOKBg04uQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});